version: "2"
services:
  app:
    build:
      args:
        user: colus
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: app:algorithms
    container_name: algorithms-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - algorithms
  nginx:
    image: nginx:alpine
    container_name: algorithms-nginx
    restart: unless-stopped
    ports:
      - 8087:8087
    volumes:
      - ./:/var/www
      - ./etc/nginx/:/etc/nginx/conf.d/
    networks:
      - algorithms

networks:
  algorithms:
    driver: bridge
